---
title: "Vansinnet i historia och litteratur"
author: "Erik Nilsson"
date: 2018-02-16T21:13:14-05:00
categories: ["Artikel"]
description: They heard! – They suspected! – they knew. [Edgar Allan Poe, Tell-Tale Heart]
tags: ["Podcast", "Historia", "Psykiatri", "Litteratur", "Kurser"]
---

Dan Carlins podcast om religiöst vansinne i den Tyska staden Mûnster under 1500-talet:

>Murderous milennial preachers and prophets take over the German city of Munster after Martin Luther unleashes a Pandora's Box of religious anarchy with the Protestant Revolution. 

&#x1F517; [Prophets of Doom](https://www.dancarlin.com/product/hardcore-history-48-prophets-of-doom/)

Distanskursen "Narrating madness" vid Umeå Universitet:

>While locating texts within their contemporary contexts as far as religion, gender and medicine, the course will engage with significant modern theoretical discussions of madness and creativity as offered by Foucault, Freud and others.

&#x1F517; [Narrating Madness](https://www.umu.se/utbildning/kurser/profilkurs-narrating-madness-in-literature-and-culture/)

Elyn Saks TED talk om Schizophreni:

>"Is it okay if I totally trash your office?" It's a question Elyn Saks once asked her doctor, and it wasn't a joke. A legal scholar, in 2007 Saks came forward with her own story of schizophrenia, controlled by drugs and therapy but ever-present. In this powerful talk, she asks us to see people with mental illness clearly, honestly and compassionately.

&#x1F517; [Elyn Saks TED talk](https://www.ted.com/talks/elyn_saks_seeing_mental_illness)

BBC podd om vanföreställningar:

> Experimental psychologist Daniel Freeman explores cases of delusion.

&#x1F517; [A History of Delusions](https://www.bbc.co.uk/programmes/p06tbbhz)
