---
title: "Mer statistik för läkarstudenter"
author: "eriknilsson"
date: 2018-12-15
categories: ["Artikel"]
tags: ["Studentprojekt", "Vetenskap"]
---

Fördjupning.

# Youtube clips om statistik 

Av Kimmo Sorjonen, KI. SPSS används.

&#x1F517; [SPSS, ANOVA, Del A, Envägs](https://www.youtube.com/watch?v=Z1SP6-3ky2Y)

&#x1F517; [SPSS, ANOVA, Del B, Multivariat](https://www.youtube.com/watch?v=SdlcqEGNTMU)

&#x1F517; [SPSS, ANOVA, Del C, Upprepade mätningar](https://www.youtube.com/watch?v=_LiqKSc4kJ8)

&#x1F517; [SPSS, ANOVA, Del D, Multivariat med upprepade mätningar](https://www.youtube.com/watch?v=k-xIyhfVdbM)

&#x1F517; [SPSS, ANOVA, Del E, Kovariansanalys](https://www.youtube.com/watch?v=6IofcgsTSmI)

&#x1F517; [SPSS, Regression, Del A, Multipel](https://www.youtube.com/watch?v=5LTQRdZQgdI)

&#x1F517; [SPSS, Regression, Del B, Kurvlinjärt](https://www.youtube.com/watch?v=P0bHAd2f4Pc)

&#x1F517; [SPSS, Regression, Del C, Interaktion](https://www.youtube.com/watch?v=gzwJmgRwP78)

&#x1F517; [SPSS, Regression, Del D, Logistisk](https://www.youtube.com/watch?v=kuKZHtrdcGw)

&#x1F517; [SPSS, Risk- och Odds-kvoter](https://www.youtube.com/watch?v=1qhk4SsEuac)

&#x1F517; [SPSS, Faktoranalys, Del A](https://www.youtube.com/watch?v=KMNXXxqF8mY)

&#x1F517; [SPSS, Faktoranalys, Del B](https://www.youtube.com/watch?v=fNCohP9dHlc)

&#x1F517; [SPSS, Faktoranalys, Del C](https://www.youtube.com/watch?v=nBlJ3LyF_Po)

&#x1F517; [SPSS, Faktoranalys, Del D](https://www.youtube.com/watch?v=r8UJnzowu1A)

&#x1F517; [SEM med AMOS, Del A, Speca modell](https://www.youtube.com/watch?v=u9y3Jm4HSIY)

&#x1F517; [SEM med AMOS, Del B, Parametrar](http://www.youtube.com/watch?v=G8uPc6ZhsWw)

&#x1F517; [SEM med AMOS, Del C, Model fit och modifiering](http://www.youtube.com/watch?v=udB_-KsdR6E)

&#x1F517; [SEM med AMOS, Del D, Effekter](http://www.youtube.com/watch?v=4xnsJoRKN_0)

&#x1F517; [SPSS, MLM (LMM), Del A, Tvärsnitt, Fixed effect](http://www.youtube.com/watch?v=Twj5NfneOCY)

&#x1F517; [SPSS, MLM (LMM), Del B, Tvärsnitt, Random effect + Interaktion](http://www.youtube.com/watch?v=kCN1m5k1RKs)

&#x1F517; [SPSS, MLM (LMM), Del C, Tvärsnitt, Kategoripresiktorer + Trevägs interaktion](http://www.youtube.com/watch?v=j8edoSdu9JI)

&#x1F517; [SPSS, MLM (LMM), Del D, Upprepade, Restructure](http://www.youtube.com/watch?v=NDJfZnioJZU)

&#x1F517; [SPSS, MLM (LMM), Del E, Upprepade, Random effect](http://www.youtube.com/watch?v=3bGiGz-50qY)

&#x1F517; [SPSS, MLM (LMM), Del F, Upprepade, Tvåvägs interaktion](http://www.youtube.com/watch?v=dRFy20HD__w)

&#x1F517; [SPSS, MLM (LMM), Del G, Upprepade, Trevägs interaktion](http://www.youtube.com/watch?v=fExWt70Dufo)

## Mall för rapportering av randomiserade kontrollerade studier: CONSORT

&#x1F517; [CONSORT webpage](http://www.consort-statement.org/)

[Consort checklist](http://www.consort-statement.org/download/Media/Default/Downloads/CONSORT%202010%20Checklist.doc)
